FirstBlog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('blogito.urls', namespace = "app_blog")),
    url(r'^admin/', include(admin.site.urls)),
]

blogito/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^calculadora/$', views.calculadora, name='calculadora'),
    url(r'^contactanos/$', views.contactanos, name='contactanos'),
    url(r'^cronometro/$', views.cronometro, name='cronometro'),
    url(r'^pregunta/$', views.pregunta, name='pregunta'),
    url(r'^imagenes/$', views.imagenes, name='imagenes'),
    url(r'^curriculum/$', views.curriculum, name='curriculum'),
    url(r'^conversor/$', views.conversor, name='conversor'),
    url(r'^noticias/$', views.noticias, name='noticias'),
    url(r'^show_post/(?P<id_post>[0-9]+)/$', 'blogito.views.show_post', name='show_post'),
    url(r'^mensaje/$', 'blogito.views.mensaje', name='mensaje'),
    url(r'^mail/$', 'blogito.views.mail', name='mail'),
    url(r'^show_categoria/(?P<id_categoria>[0-9]+)/$', 'blogito.views.show_categoria', name='show_categoria'),
]

blogito/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Noticia(models.Model):
    class Meta:
        verbose_name = "Noticia"
        verbose_name_plural = "Noticias"
        ordering=['-fecha']
    titulo = models.CharField(u"Titulo",max_length=200)
    noticia = models.TextField(u"Noticia")
    descripcion = models.TextField(u"Descripcion")
    fecha = models.DateTimeField(u'Fecha del Post',auto_now_add=True)
    categoria = models.ManyToManyField('Categoria')
    published = models.BooleanField(u'Publicado?', default=True)
    autor = models.ForeignKey(User)
    def __str__(self):
        return self.titulo

class Contacto(models.Model):
    class Meta:
        verbose_name = "Contacto"
        verbose_name_plural = "Contactos"
    asunto = models.CharField(u'asunto', max_length=100)
    mail = models.CharField(u'Mail', max_length=100)
    mensaje = models.TextField(u'Mensaje')
    def __str__(self):
        return self.mail

class Categoria(models.Model):
    nombre = models.CharField(u'Título de la Categoría', max_length=100)
    descripcion = models.CharField(u'Descripción de la Categoría', max_length=256)
    def __str__(self):
        return self.nombre

class Comentario(models.Model):
    class Meta:
        verbose_name = "Comentario"
        verbose_name_plural = "Comentarios"
        ordering=['-fecha']
    autor = models.CharField(u'Nombre', max_length=100)
    mensaje = models.TextField(u'Mensaje')
    post = models.ForeignKey(Noticia)
    fecha = models.DateTimeField(u'Fecha del Post',auto_now_add=True)
    def __str__(self):
        return self.autor

blogito/views.py
# -*- coding: utf-8 -*-
from django.template import RequestContext
from django.shortcuts import render_to_response, render, redirect
from blogito.models import Noticia, Comentario, Contacto, Categoria
from django.views.decorators.csrf import ensure_csrf_cookie
from django.core.mail import send_mail
import smtplib
@ensure_csrf_cookie
# Create your views here.

def calculadora(request):
    context = RequestContext(request)
    return render_to_response('calculadora.html',context)

def noticias(request):
    context = RequestContext(request)
    noticias = Noticia.objects.filter(published = True)
    categorias = Categoria.objects.all()
    no_noticias=False
    if noticias.__str__()=="[]":
        no_noticias=True
    selected="Todos"
    return render_to_response('noticias.html', {'noticias':noticias,"no_noticias":no_noticias,"categorias":categorias,"seleccionado":selected}, context)

def contactanos(request):
    context = RequestContext(request)
    return render_to_response('contactanos.html', context)

def cronometro(request):
    context = RequestContext(request)
    return render_to_response('cronometro.html', context)

def curriculum(request):
    context = RequestContext(request)
    return render_to_response('curriculum.html', context)

def conversor(request):
    context = RequestContext(request)
    return render_to_response('conversor.html', context)

def imagenes(request):
    context = RequestContext(request)
    return render_to_response('imagenes.html', context)

def index(request):
    context = RequestContext(request)
    return render_to_response('index.html', context)

def pregunta(request):
    context = RequestContext(request)
    return render_to_response('pregunta.html', context)

def show_post(request, id_post):
    context = RequestContext(request)
    post = Noticia.objects.get(id=id_post)
    comentarios = Comentario.objects.filter(post_id = id_post)
    return render_to_response('show_post.html',{'post':post, 'comentarios':comentarios}, context)

def mensaje(request):
    context = RequestContext(request)
    if request.method == 'POST':
        #ESTO OBTIENE LOS DATOS QUE VIENEN EL EL "HTTP POST" NO TIENE NADA QUE VER CON LOS MODELS NAADAADADADA 
        nombre= request.POST.get('nombre')
        mensaje= request.POST.get('mensaje')
        id_post= request.POST.get('id')
        #-------------------------------------
        #ACA CREAS UN MODEL Y LE METES LOS DATOS QUE CONSEGUIMOS ANTES, ANTES ME REFIERO A LO DE ARRIBA
        comentario = Comentario()
        comentario.autor = nombre
        comentario.mensaje = mensaje
        comentario.post_id = id_post
        #ACA GUARDAMOS EL COMENTARIO QUE CREAMOS
        comentario.save()
    
    #ACA FILTRAMOS TODOS LOS COMENTARIOS QUE PERTENEZCAN AL POST QUE ESTAMOS VIENDO PARA PASARSELO 
    id_post= request.POST.get('id')
    comentarios = Comentario.objects.filter(post_id = id_post)
    return render_to_response('mensajes.html',{'comentarios':comentarios}, context)

def mail(request):
    context = RequestContext(request)
    if request.method == 'POST':
        #Guarda el contacto en la base de datos... por que si
        mail= request.POST.get('mail')
        mensaje= request.POST.get('mensaje')
        asunto= request.POST.get('asunto')
        contacto = Contacto()
        contacto.asunto = asunto
        contacto.mail = mail
        contacto.mensaje = mensaje
        contacto.save()
        #Para enviar Mail ami mismo diciendo como asunto quien lo manda y sobre que y en el contenido lo que el usuario dice
        username = "matidemayi@gmail.com"
        password = "rewstrew"
        fromaddr = "matidemayi@gmail.com"
        toaddr = "matidemayi@gmail.com"
        msg = "Subject: Mensaje de "+mail+", Sobre: "+asunto+"\n\n"+mensaje
        server = smtplib.SMTP_SSL('smtp.googlemail.com:465')
        server.login(username, password)
        server.sendmail(fromaddr, [toaddr], msg)
        server.quit()

    return render_to_response('contactanos.html', context)

def show_categoria(request, id_categoria):
    print "entro"
    context = RequestContext(request)
    noticias = Noticia.objects.filter(published = True, categoria=id_categoria)
    categorias = Categoria.objects.all()
    categoria = Categoria.objects.filter(id=id_categoria)
    no_noticias=False
    if noticias.__str__()=="[]":
        no_noticias=True
    return render_to_response('noticias.html', {'noticias':noticias,"no_noticias":no_noticias,"categorias":categorias,"selected":categoria}, context)

blogito/templates/base.html
{% load staticfiles %}
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui-1.11.4.custom/jquery-ui.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui-1.11.4.custom/jquery-ui.theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/clean-blog.css' %}">
    

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block css %}    
    {% endblock %}
</head>
<body>
<!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom ">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'app_blog:index' %}">Home</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'app_blog:noticias' %}" >Noticias</a>
                    </li>
                    <li>
                        <a href="{% url 'app_blog:curriculum' %}" >Curriculum</a>
                    </li>
                    <li>
                        <a href="{% url 'app_blog:calculadora' %}" >Calculadora</a>
                    </li>
                    <li>
                        <a href="{% url 'app_blog:contactanos' %}" >Contactanos</a>
                    </li>
                    <li>
                        <a href="{% url 'app_blog:conversor' %}" >Conversor</a>
                    </li>
                    <li>
                        <a href="{% url 'app_blog:imagenes' %}"  >Imagenes</a>
                    </li>
                    <li>
                        <a href="{% url 'app_blog:pregunta' %}">Pregunta</a>
                    </li>
                    <li>
                        <a href="{% url 'app_blog:cronometro' %}">Cronometro</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
{% block header %}
{% endblock %}
<div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    {% block content %}
    {% endblock %}
            </div>
        </div>
</div>

    <footer >        
        <div class="container" >
            
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <p class="copyright text-muted">
                        De los creadores de <a href="http://tulp-project.appspot.com/">Tulp</a>&copy; :  Lince's Blog&copy; <i class="fa fa-university "></i>
                    </p>
                </div>
            </div>
        </div>
    </footer>
    <!-- jQuery -->
    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    
        {% block script %}
        {% endblock %}
</body>
    

</html>

    

blogito/templates/calculadora.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
            <div id="Calculadora" class="col-md-4 col-md-offset-5" >
            <input type="text"  id="pantallita" value="" /> <br/>
            <input type="button" class="btnCalc" id="btn1" onclick="ejecutar(this);" value="1"/>
            <input type="button" class="btnCalc" id="btn2" onclick="ejecutar(this);" value="2"/>
            <input type="button" class="btnCalc" id="btn3" onclick="ejecutar(this);" value="3"/>
            <input type="button" class="btnCalc" id="btnMas" onclick="ejecutar(this);" value="+"/>
            <br/>
            <input type="button" class="btnCalc" id="btn4" onclick="ejecutar(this);" value="4"/>
            <input type="button" class="btnCalc" id="btn5" onclick="ejecutar(this);" value="5"/>
            <input type="button" class="btnCalc" id="btn6" onclick="ejecutar(this);" value="6"/>
            <input type="button" class="btnCalc" id="btnMenos" onclick="ejecutar(this);" value="-"/>
            <br/>
            <input type="button" class="btnCalc" id="btn7" onclick="ejecutar(this);" value="7"/>
            <input type="button" class="btnCalc" id="btn8" onclick="ejecutar(this);" value="8"/>
            <input type="button" class="btnCalc" id="btn9" onclick="ejecutar(this);" value="9"/>
            <input type="button" class="btnCalc" id="btnPor" onclick="ejecutar(this);" value="*"/>
            <br/>
            <input type="button" class="btnCalc" id="btnP" onclick="ejecutar(this);" value="."/>
            <input type="button" class="btnCalc" id="btn0" onclick="ejecutar(this);" value="0"/>
            <input type="button" class="btnCalc" id="btnR" onclick="ejecutar(this);" value="="/>
            <input type="button" class="btnCalc" id="btnDividir" onclick="ejecutar(this);" value="/"/>
        </div>
{% endblock %}

{% block script %}
<script>
    var availableTags = ["Noticias","Curriculum","Contactanos","Calculadora","Conversor","Pregunta","Imagenes","Cronometro"
    ];       
        
    isLast = false;
        
    function ejecutar(jose){
            value = jose.value;
            pant = document.getElementById("pantallita");
            console.log(value);
            if(value != "="){
                pant.style.textAlign= "left";
                if(isLast){
                    pant.setAttribute("value",value);
                }else{
                    valPant = document.getElementById("pantallita").value;
                    pant.setAttribute("value",valPant+value);
                }

                isLast=false;
            }
            if(value == "="){
                valPant = document.getElementById("pantallita").value;
                pant.setAttribute("value",eval(valPant));
                pant.style.textAlign= "right";
                isLast=true;
            }
        }
    $( "#btnBusqueda" ).click(function() {
        direccion = $("#busqueda").val();
        window.location.href = direccion+".html";
    });
    </script>
{% endblock %}

blogito/templates/contactanos.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
	<form action="{% url 'app_blog:mail' %}" method="POST" name="sentMessage" id="contactForm">
	{% csrf_token %}
        <div class="form-group">
			  <label for="usr">Mail:</label>
			  <input type="text" class="form-control" name="mail" id="mail">
		</div>
		<div class="form-group">
			  <label for="pwd">Asunto:</label>
			  <input type="text" id="asunto"class="form-control" name="asunto">
		</div>
		 <div class="form-group">
		  <label for="comment">Mensaje:</label>
		  <textarea class="form-control" rows="5" id="mensaje" name="mensaje"></textarea>
		</div>
		<input type="submit" id="send"value="Submit">
	</form>
{% endblock %}

{% block script %}
<script>
	
</script>
{% endblock %}

blogito/templates/conversor.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
           <div id="MoneyConvert">
                <select id="From" class="col-xs-5 selectContainer">
                    <option value="1">Dollar</option>
                    <option value="2">Euro</option>
                    <option value="3">ARS</option>
                    <option value="4">CHI</option>
                    <option value="5">UYU</option>
                </select>
                <input type="number" id="ToConv"/><br/>
                <select id="To" class="col-xs-5 selectContainer">
                    <option value="1">Dollar</option>
                    <option value="2">Euro</option>
                    <option value="3">ARS</option>
                    <option value="4">CHI</option>
                    <option value="5">UYU</option>
                </select>
                <input type="number" id="Convertion"/><br/>
                
                <input type="button" value="Convertir" onclick="coso()"/>
            </div>   
{% endblock %}

{% block script %}
<script>
    var availableTags = ["Noticias","Curriculum","Contactanos","Calculadora","Conversor","Pregunta","Imagenes","Cronometro"
    ];
    $( "#busqueda" ).autocomplete({
      source: availableTags
    });

        function coso() {
            from = document.getElementById("From");
            valueFrom = from.options[from.selectedIndex].value;
            console.log(valueFrom);
            to = document.getElementById("To");
            valueTo = to.options[to.selectedIndex].value;
            number = document.getElementById("ToConv").value;
            
            outputConvertion = document.getElementById("Convertion");
            euro = 0.93367;
            dollar = 1;
            ARS = 8.86387;
            CHI = 611.143;
            UYU = 25.7813;
            switch(valueFrom + "-" + valueTo){
                case "1-1":  outputConvertion.value = number; break;
                case "2-2":  outputConvertion.value = number; break;
                case "3-3":  outputConvertion.value = number; break;
                case "4-4":  outputConvertion.value = number; break;
                case "5-5":  outputConvertion.value = number; break;

                case "1-2":  outputConvertion.value = dollar*euro*number;break;
                case "1-3":  outputConvertion.value = dollar*ARS*number;break;
                case "1-4":  outputConvertion.value = dollar*CHI*number;break;
                case "1-5":  outputConvertion.value = dollar*UYU*number;break;

                case "2-1":  outputConvertion.value = number/euro*dollar;break;
                case "2-3":  outputConvertion.value = number/euro*ARS;break;
                case "2-4":  outputConvertion.value = number/euro*CHI;break;
                case "2-5":  outputConvertion.value = number/euro*UYU;break;

                case "3-1":  outputConvertion.value = number/ARS*dollar;break;
                case "3-2":  outputConvertion.value = number/ARS*euro;break;
                case "3-4":  outputConvertion.value = number/ARS*CHI;break;
                case "3-5":  outputConvertion.value = number/ARS*UYU;break;

                case "4-1":  outputConvertion.value = number/CHI*dollar;break;
                case "4-2":  outputConvertion.value = number/CHI*euro;break;
                case "4-3":  outputConvertion.value = number/CHI*ARS;break;
                case "4-5":  outputConvertion.value = number/CHI*UYU;break;

                case "5-1":  outputConvertion.value = number/UYU*dollar;break;
                case "5-2":  outputConvertion.value = number/UYU*euro;break;
                case "5-3":  outputConvertion.value = number/UYU*ARS;break;
                case "5-4":  outputConvertion.value = number/UYU*CHI;break;
                default:;
            }
        }

        $( "#btnBusqueda" ).click(function() {
            direccion = $("#busqueda").val();
            window.location.href = direccion+".html";
        });
        </script>
{% endblock %}

blogito/templates/cronometro.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
            <input id="cronometro" value=0></input><br/>
            <input type="button" class="cronButton" id="btnIniciar" onclick="iniciar()" value="Inicio"/><br/>
            <input type="button" class="cronButton" id="btnPausa" onclick="pausa()" value="Pausa"/><br/>
            <input type="button" class="cronButton" id="btnTerminar" onclick="terminar()" value="Parar"/><br/>
            <input type="button" class="cronButton" id="btnVuelta" onclick="vuelta()" value="Vuelta"/><br/>
            <p id="p1"> </p>
{% endblock %}
{% block script %}
<script>
    hrs=0;
    min=0;
    seg=0;
    mseg=0;
    function horas(){
        hrs+=1;
    }
    function minutos() {
        min+=1;
        if(min>59){
            min=0;
        }        
        
    }
    function segundos(){
        seg+=1;
        if(seg>59){
            seg=0;
        }        

    }
    function milisegundos(){
        mseg+=1;
        if(mseg>99){
            mseg=0;
        }
        document.getElementById("cronometro").setAttribute("value",hrs+":"+min+":"+seg+":"+mseg);
    }
    
    var h;
    var m;
    var s;
    var ms;
    
        
    estado = 0;
    function iniciar(){
        if(estado==0){
            terminar();
            document.getElementById("p1").innerHTML = "";
        }

        h=setInterval(function () {horas()}, 3600000);
        m=setInterval(function () {minutos()}, 60000);
        s=setInterval(function () {segundos()}, 1000);
        ms=setInterval(function () {milisegundos()}, 1);
    }
    function pausa(){
        clearInterval(h);
        clearInterval(m);
        clearInterval(s);
        clearInterval(ms);
        document.getElementById("btnIniciar").setAttribute("value","Renaudar");
        estado=1;
    }
    function terminar(){
        window.clearInterval(h);
        window.clearInterval(m);
        window.clearInterval(s);
        window.clearInterval(ms);
        hrs=0;
        min=0;
        seg=0;
        mseg=0;
        document.getElementById("cronometro").setAttribute("value",hrs+":"+min+":"+seg+":"+mseg);
        document.getElementById("btnIniciar").setAttribute("value","Iniciar");
        estado=0;
    }
    function vuelta(){
        valor = document.getElementById("cronometro").getAttribute("value");
        console.log(valor);
        valor = valor + "<br/>";
        document.getElementById("p1").innerHTML = document.getElementById("p1").innerHTML+valor;       
    }
</script>
{% endblock %}

blogito/templates/curriculum.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
            <div style="float:left; width:20%;">
            <img src="{% static 'css/Images/lince.jpg' %}" width='150' height='150'>
        </div>
        <div style="float:left; width:70%;">
            <h2> Ulises Torrella</h>
            <p align="right"> <b>Edad</b>: 17<br>
                <b>Institucion</b>: ITS Villada<br>
                <b>Profecion</b>: Lince<br>
                <b>Ciudadania</b>: Argentina<br>
            </p>
        </div>
       
{% endblock %}

blogito/templates/imagenes.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
            <img id="Cuadro" width='900' height='450' src="{% static 'css/img/img3.jpg' %}">
            <progress  id="pb" value="0" max="100" style="float: left; margin-left:0px;" />
{% endblock %}

{% block script %}
<script>
        setInterval(function () {cambiarFoto()}, 5000);
        setInterval(function () {avancePb()}, 50);
        actual=5;
        function avancePb(){
            progress=document.getElementById("pb");
            progress.value = progress.value+1;
        }
        function cambiarFoto() {
            console.log("antes");
            numero = Math.floor((Math.random() * 10)+1);
            while(actual==numero){
                numero = Math.floor((Math.random() * 10)+1);
            }
            document.getElementById("Cuadro").setAttribute("src","{% static 'css/img/img' %}"+numero+'.jpg');
            progress=document.getElementById("pb");
            progress.value = 0;
            actual=numero;
            console.log("despues");
        }
        </script>

{% endblock %}

blogito/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block header%}
<header class="intro-header" style="background-image: url({% static 'css/Images/lince-durmiendo.jpg' %})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Lince Blog</h1>
                        <hr class="small">
                        <span class="subheading">Blog de linces para linces</span>
                    </div>
                </div>
            </div>
        </div>
</header>
{% endblock %}
{% block content %}
    <h3>Bienvenidos a mi blog<small></small></h3>
    <em>"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."
    "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"
    </em>
{% endblock %}

blogito/templates/mensajes.html
{% load staticfiles %}

{% for comentario in comentarios %}

            <div class="testimonials">
                <div class="active item">
                  <blockquote><h4 style="color:black;">{{comentario.mensaje}}</h4></blockquote>
                  <div class="carousel-info">
                    <img alt="" src="{% static 'css/Images/lince.jpg' %}" class="pull-left">
                    <div class="pull-left">
                      <span class="testimonials-name">{{comentario.autor}}</span>
                      <span class="testimonials-date">{{comentario.fecha}}</span>
                    </div>
                  </div>
                </div>
            </div>
{% endfor %}

blogito/templates/noticias.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="col-md-10 col-md-offset-0">
            <div class="btn-group" style="float:right;">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% for s in selected %}
                {{s.nombre}}
                {% endfor %} {{seleccionado}} <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                {% for categoria in categorias %}
                <li><a title='{{categoria.descripcion}}' href="{% url 'app_blog:show_categoria' categoria.id %}">{{categoria.nombre}}</a></li>
                {% endfor %}
              </ul>
            </div>
            {% if no_noticias %}
                <img width='100%' height='70%' src="{% static 'css/Images/nonoticias.png' %}">
            {% else %}
                <ul style="list-style-type:none">
                {% for noticia in noticias %}
                <li>
                <div "{% url 'app_blog:show_post' noticia.id %}" class="post-preview">
                        <h2  class="post-title"><a href="{% url 'app_blog:show_post' noticia.id %}">
                            {{ noticia.titulo}}</a>
                        </h2>
                        <h3 class="post-subtitle">
                            {{noticia.descripcion}}
                        </h3>
                </div>
                </li>
                {% endfor %}
                </ul>  
            {% endif %}
        

            </div>
    </div>
</div>
{% endblock %}

blogito/templates/show_post.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="container">
            <ul style="list-style-type:none">
                <li>
                <div class="col-md-8 col-md-offset-0" style="margin-left:-5%">
                        <h2 >
                            {{post.titulo}}
                        </h2>
                        <p style="text-align:right;color:blue">
                            Posted by {{post.autor}}<br>
                            {{post.fecha}}
                        </p>
                        <p>
                            {{post.noticia}}
                        </p>
                        
                </div>
                </li>  
            </ul>          
    </div>
    <hr class="featurette-divider"></hr>
    <hr class="featurette-divider"></hr>

        <div id="mensajes" style="background:lightgrey;"class="row">
                {% include "mensajes.html" %}
        </div>  
    <hr class="featurette-divider"></hr>
    <hr class="featurette-divider"></hr>
    {% csrf_token %} 
    <div style="background:;">
        <div class="form-group" >
          <label for="usr">Name:</label>
          <input type="text" id="nombre"class="form-control" id="usr">
        </div>
         <div class="form-group">
          <label for="comment">Comment:</label>
          <textarea class="form-control" id="comentario"rows="5" id="comment"></textarea>
        </div>
        <input type="button" id="send" value="Submit">
        </div>
    </div>

</div>
{% endblock %}
{% block script %}
<script>
    $("#send").click(function comentario(){
        var data={
            csrfmiddlewaretoken: '{{ csrf_token }}',
            nombre:$("#nombre").val(),
            mensaje:$("#comentario").val(),
            id:'{{post.id}}',
        }
        $.ajax({
            method: "POST",
            url: "{% url 'app_blog:mensaje' %}",
            data: data,
            success:function(result){
                $("#mensajes").html(result);
                nombre:$("#nombre").val("");
                mensaje:$("#comentario").val("");
            },
            error: function(e){
                console.log(e.responseText);
            }
        });

    });
</script>
{% endblock %}